### ISSUE TITLE
Error after enabling mod.

### ISSUE THREAD

**Issue by BaconEggCheese777** [Sixdd6/Right-Tool-for-the-Job-Rebalanced#1]
Could not resolve cross-reference: No Verse.DesignationCategoryDef named Production2 found to give to Verse.ThingDef RTFTJToolBench
Cannot call ItemFromXmlFile with resolveCrossRefs=true while loading is already in progress.

**Comment by Sixdd6** [comment]
Thank you for the report, the fix is up now.
