### ISSUE TITLE
error after enabling mod

### ISSUE THREAD

**Issue by Scout91** [Sixdd6/Right-Tool-for-the-Job-Rebalanced#4]
i get this issue after i enable this mod

![error rimworld](https://user-images.githubusercontent.com/18028006/30831218-f59c357a-a246-11e7-88b9-f183bdcc51db.PNG)

can you please fix it

**Comment by Sixdd6** [comment]
The errors won't hurt your game but yeah I'll get a fix up asap

**Comment by Scout91** [comment]
Oke and thanks for the quick response

**Comment by Sixdd6** [comment]
fix is up, have fun 😄
